### ISSUE TITLE
Minecraft crashes upon launch

### ISSUE THREAD

**Issue by DecimJaeger** [indi-code/cauldron-brewing#1]
Whenever I try to launch the game it crashes, here is the crash-report:

// My bad.

Time: 9/1/19 12:15 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.NoSuchMethodError: io.github.indicode.fabric.potatocore.util.AdvancedIngredient.ofItems([Lnet/minecraft/class_1935;)Lio/github/indicode/fabric/potatocore/util/AdvancedIngredient;
		at io.github.indicode.fabric.cauldronbrew.recipe.CauldronRecipeManager.init(CauldronRecipeManager.java:217)
		at io.github.indicode.fabric.cauldronbrew.CauldronBrewing.onInitialize(CauldronBrewing.java:30)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2633003280 bytes (2511 MB) / 3554672640 bytes (3390 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx6144m
	Fabric Mods: 
		cauldronbrew: Cauldron Brewing 0.1.0
		fabric: Fabric API 0.3.2+build.218-1.14
		fabric-api-base: fabric-api-base 0.1.0+b494ebeb42
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.40+build.1
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.13+68fade5542
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.3+b02deb0042
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.6.1+build.164
		minecraft: Minecraft 1.14.4
		modmenu: Mod Menu 1.7.9+build.118
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.40
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.2
		potatocore: PotatoCore 0.2.0
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by indi-code** [comment]
Oh yea, thats a problem with not updating potatocore... (My bad not yours) Will fix.
